### register new user
POST http://localhost:88/api/v1/register
Content-Type: application/json

{
  "fullname": "John Doe",
  "email": "johndoe@example.com",
  "password": "JohnDoe@12345"
}

### Login to get token
# @name login
POST http://localhost:88/api/v1/auth/login
Content-Type: application/json

{
  "email": "johndoe@example.com",
  "password": "JohnDoe@12345"
}

### Assign the token to a variable
@authToken = {{login.response.body.data.token}}

### Create a Todo (Protected Route)
POST http://localhost:88/api/v1/todos
Content-Type: application/json
Authorization: Bearer {{authToken}}

{
  "title": "Learn Jest",
  "description": "Finish the unit testing module"
}

### fetch all todos
GET http://localhost:88/api/v1/todos
Authorization: Bearer {{authToken}}

### fetch todo
GET http://localhost:88/api/v1/todos/2
Authorization: Bearer {{authToken}}

### update todo
PUT http://localhost:88/api/v1/todos/2
Content-Type: application/json
Authorization: Bearer {{authToken}}

{
  "description": "Read more on Jest so that you can understand Jest better"
}