### register new user
POST http://localhost:88/api/v1/auth/register
Content-Type: application/json

{
  "fullname": "Lukman Bello",
  "email": "Bellolukman@gmail.com",
  "password": "Bella$12345A$$A"
}

### Login to get token
# @name login
POST http://localhost:88/api/v1/auth/login
Content-Type: application/json

{
  "email": "Bellolukman@gmail.com",
  "password": "Bella$12345A$$A"
}

### Assign the token to a variable
@authToken = {{login.response.body.token}}

### Create a Todo (Protected Route)
POST http://localhost:88/api/v1/todos
Content-Type: application/json
Authorization: Bearer {{authToken}}

{
  "title": "Learn React Native",
  "description": "Work till I get a good system to complete my react native course and start building mobile applications"
}

### fetch all todos
GET http://localhost:88/api/v1/todos?page=1&limit=10
Authorization: Bearer {{authToken}}

### fetch todo
GET http://localhost:88/api/v1/todos/5
Authorization: Bearer {{authToken}}

### update todo
PUT http://localhost:88/api/v1/todos/3
Content-Type: application/json
Authorization: Bearer {{authToken}}

{
  "title": "Continue learning React Native",
  "description": "Try to master it more"
}

### delete todo
DELETE http://localhost:88/api/v1/todos/6
Authorization: Bearer {{authToken}}